### ISSUE TITLE
Tag 2.2.3 Release

### ISSUE THREAD

**Issue by PSchmiedmayer** [wickwirew/Runtime#102]
Hi @wickwirew ,
With #88, #94, #95, #99, #100, and #101 merged, it would be great if you can tag a new release so Swift Packages depending on Runtime can use a stable version instead of pointing to the current main branch.
I would suggest `2.2.3` as the release tag as there have been no breaking changes in the PRs mentioned above.
Thanks a lot for the time and effort in maintaining the Runtime project! 💪

**Comment by wickwirew** [comment]
Done! Misunderstood the date on the tag so I ended up doing it twice 😅 so the release is `2.2.4`

**Comment by PSchmiedmayer** [comment]
@wickwirew Thanks a lot!
