### ISSUE TITLE
overwrite version 2.2.6

### ISSUE THREAD

**Issue by jaredh159** [wickwirew/Runtime#112]
did you possibly just overwrite the `2.2.6` release?  i'm getting build failures saying:

```
error: 'runtime': Revision 275fbf843bf4198a732eacde4eff1b21e378edc6 for runtime remoteSourceControl https://github.com/wickwirew/Runtime.git version 2.2.6 does not match previously recorded value ea112a73f7a8772a92b125ceeaaf61f1844466bd
```

and it looks like there is a new git sha for 2.2.6, but i think 2.2.6 has been out a while...  🤔

thanks for the wonderful library!

**Comment by wickwirew** [comment]
yeaaaa... I wasnt thinking on that one 🙃. Cocoapods was having issues. Sorry about that!

**Comment by jaredh159** [comment]
no problem, i won't ask for my money back. :) 

yeah, i think probably tagging `2.2.7` might be best, since otherwise the fix for SPM is to manually update the `Package.resolved`, and also I had to blow away `~/.swiftpm` and `.build` to get the build compiling again (even after running `swift package reset` and `swift package purge-cache`)

**Comment by wickwirew** [comment]
sorry, didnt see your response. But just pushed 2.2.7. Sorry about all of this!

**Comment by jaredh159** [comment]
no problem. thanks for the new tag 👍
