### ISSUE TITLE
Broken on Swift 4.1

### ISSUE THREAD

**Issue by jseibert** [wickwirew/Runtime#13]
Swift 4.1 apparently includes ABI changes that cause this library to fail completely. ~All tests crash with EXC_BAD_ACCESS.

Instructions for grabbing the latest Swift 4.1 snapshot here:

https://gist.github.com/tanner0101/cdb77c7f58d53af2ba2da5d39415389a

**Comment by wickwirew** [comment]
Thanks for the issue, been meaning to update it for swift 4.1. I've create a `swift-4.1` branch. So hopefully soon it will have support!

**Comment by wickwirew** [comment]
I have updated the `swift-4.1` branch, now all tests pass. Let me know if you have any more issues. Going to merge `swift-4.1` to master once Xcode 9.3 is out of beta.

**Comment by jseibert** [comment]
Wow you're fast, awesome! Works perfectly for me.

**Comment by wickwirew** [comment]
Glad to hear it! Thanks for trying it out again.
