### ISSUE TITLE
why class is 4096? not 2047

### ISSUE THREAD

**Issue by luoqisheng** [wickwirew/Runtime#15]
just a questoin! ref: https://github.com/apple/swift/blob/6a9e1f2b3e3ea27121a939140d4d6615ce78f1bb/include/swift/ABI/MetadataValues.h

**Comment by wickwirew** [comment]
Checkout [Type Metadata](https://github.com/apple/swift/blob/master/docs/ABI/TypeMetadata.rst#common-metadata-layout). Specifically the Class Metadata where it talks about the kind

**Comment by luoqisheng** [comment]
Thanks!.  Given a pointer ,how to tell which type it blongs to.  i.e: class or just malloc block.

**Comment by wickwirew** [comment]
Thats not entirely possible. No metadata is stored with an object. A class will have an isa pointer however

**Comment by luoqisheng** [comment]
Thanks , I am trying to figure  out how does the memory debugger works. And I found what you did was so cool. Anyway, thanks again.
