### ISSUE TITLE
Swift 4.1  EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by ArtemBogush** [wickwirew/Runtime#24]
Trying to set values with the lib but getting  EXC_BAD_ACCESS (code=1, address=0x0) error

```
    func setFieldValue(_ value: Any) {

        if let editFieldName = editFieldName1, let _ = targetObject {
            var object = targetObject!;
            if dataItemTypeInfo == nil{
                dataItemTypeInfo = try! typeInfo(of: type(of:object));
            }
            
            let property = try! dataItemTypeInfo!.property(named: editFieldName)
            try! property.set(value: value, on: &object)
        }
    }


```
It crashes on the last line: `try! property.set(value: value, on: &object)` and till then all values looks correct (dataItemTypeInfo, property, value, targetObject, editFieldName)

My pod: 

pod 'Runtime', :git => 'https://github.com/wickwirew/Runtime.git', :branch => 'swift-4.1'  

Xcode 9.3.1
Swift 4.1

Am I doing something wrong?

![screen shot 2018-06-20 at 6 06 21 pm](https://user-images.githubusercontent.com/8145834/41670487-b6e2f940-74b4-11e8-9da2-7b56429aba4d.png)

**Comment by wickwirew** [comment]
Sorry im unable to reproduce the issue. Can you give the latest release a try? That branch I think may be a bit behind. It was mainly for the migration from swift 4 to 4.1. And a crash has been fixed recently.
So change your podfile to `pod 'Runtime', '~> 0.7.1'`
If that doesnt work or at least give a better error could you provide some better sample code to help reproduce it?

**Comment by ArtemBogush** [comment]
I was trying the master branch first actually which gave me that error before switching to swift4.1. Will give it another try and let you know how it goes.
