### ISSUE TITLE
crash occurs if the base class is NSObject

### ISSUE THREAD

**Issue by Duck528** [wickwirew/Runtime#25]
```swift 
class User: NSObject {
    let id: Int = 0
    let username: String = ""
    let email: String = ""
}

let info = try typeInfo(of: User.self) // crash occurs 
let property = try info.property(named: "username")
print("name: \(property.name)")
print("type: \(property.type)")
```

how fix this problem? and is there any plan to support objective-c language?

**Comment by Duck528** [comment]
Thank you, i confirmed that it works well. 
but real my problem is not fixed yet. 

my real problem is below 
```swift
class RealmUser: Object {
    @objc dynamic var id: Int = 0
    @objc dynamic var username: String = ""
    @objc dynamic var email: String = ""
}

let realmInfo = try typeInfo(of: RealmUser.self)
let realmProperty = try realmInfo.property(named: "username")
print("name: \(realmProperty.name)")
print("type: \(realmProperty.type)")
```

can this problem be solved? i hope to be.. 
thank you!!

**Comment by wickwirew** [comment]
hmmmm im not to sure. Id have to set up a realm project. However I wouldn't use this project with Realm. Setting a property via reflection with this lib wont actually trigger realm to actually save it. Out of curiosity whats the use case?

**Comment by Duck528** [comment]
After read your comment, It seems to useless.. 

but if runtime library applied to unsupported type, I think it would be better to print error message instead of crash.  

and that use case just simple class inheritance.. sorry (T_T) 
thank you for your kindness.
