### ISSUE TITLE
CRuntime can be removed

### ISSUE THREAD

**Issue by NSExceptional** [wickwirew/Runtime#39]
Simply include this function definition somewhere in this project:

```swift
@_silgen_name("swift_getTypeByMangledNameInContext")
func swift_getTypeByMangledNameInContext(
    _ typeNameStart: UnsafeMutablePointer<Int8>,
    _ typeNameLength: Int32,
    _ context: UnsafeRawPointer?,
    _ genericArgs: UnsafePointer<UnsafeRawPointer?>?
) -> UnsafeRawPointer?
```

**Comment by NSExceptional** [comment]
Closing this issue because it has occurred to me that using a bridging header is more formal than using the private `@_silgen_name`

**Comment by wickwirew** [comment]
Back in swift 4.2 we had something similar to that for the `swift_getFieldAt` call, which caused linking problems on linux. Moving it to a separate module was the ultimate fix. 

Heres the thread: https://github.com/wickwirew/Runtime/issues/18#issuecomment-426062296

If we can remove it I'd love too though

**Comment by NSExceptional** [comment]
Yeah, sounds like what Joe told me. [Relevant thread](https://forums.swift.org/t/should-anyone-be-using-silgen-name-outside-of-the-standard-library-developers/19396/18?u=nsexceptional) on the forums.
