### ISSUE TITLE
Question: didSet of properties changes

### ISSUE THREAD

**Issue by cooksimo** [wickwirew/Runtime#48]
This is a (possible stupid) question. 

When modifying values `didSet` is not called on the property, I assume this is due to the way the property itself is actually mutated and there is nothing that can be done about this?

Thanks!

**Comment by wickwirew** [comment]
Not a stupid question. To set a property we grab a pointer directly to the value and set it directly, so this will bypass the `didSet`. Unfortunately as of now there is no way around this.
