### ISSUE TITLE
Optional type crash

### ISSUE THREAD

**Issue by bacherma** [wickwirew/Runtime#54]
typeInfo(of:) crashes on optional types. e.g.

`Runtime.RuntimeError.couldNotGetTypeInfo(type: Swift.Optional<Swift.Double>, kind: Runtime.Kind.optional)`

Reading them as enum seems to work fine. Is there a reason why this is not supported?

**Comment by wickwirew** [comment]
Just an over sight. Fixed in https://github.com/wickwirew/Runtime/pull/56
