### ISSUE TITLE
Is it possible to Element type of Array Properties?

### ISSUE THREAD

**Issue by wildthink** [wickwirew/Runtime#59]
Basically, I'm trying to provide KeyValueCoding capability including the array operations.

I'm trying to navigate the key path through a property that is an Array. If the propertyInfo could provide the type of the Array Element that may do the trick.

**Comment by wickwirew** [comment]
Sorry if im misunderstanding, but to get the `Element` type you can just do:
```swift
let info = try typeInfo(of: [Int].self)
let elementType = info.genericTypes.first
```

**Comment by wildthink** [comment]
Yes, I didn't understand how the API. I was looking for the `fn_info`. Just missed the need for the extra step. When wouldn't the `fn_info` be available? Ever?
```
        let info = try typeInfo(of: Person.self)
        let favoriteNumbers = try info.property(named: "favoriteNumbers")
        let fn_info = try typeInfo(of: favoriteNumbers.type)
        Swift.print(fn_info.genericTypes)
```

**Comment by wildthink** [comment]
Thanks.
