### ISSUE TITLE
Calling function of a class

### ISSUE THREAD

**Issue by alexsteinerde** [wickwirew/Runtime#63]
Hey,
great library!
But is it also possible to call a function of an object with parameters?

**Comment by wickwirew** [comment]
I actually worked on this a few days ago. I can get a pointer to the vtable and all get of the symbol names, however there is no way to demangle them unfortunately, so they are kind of useless. 

I saw a proposal to add a demangle function to the stdlib, but no progress has been made on it. Until then I don’t see a way to do it.

**Comment by alexsteinerde** [comment]
Ok thanks for the answer. So I think as this not possible at the moment I'll close the issue until I hear something new in the Swift forum about function reflection.

**Comment by starFelix** [comment]
> I actually worked on this a few days ago. I can get a pointer to the vtable and all get of the symbol names, however there is no way to demangle them unfortunately, so they are kind of useless.
> 
> I saw a proposal to add a demangle function to the stdlib, but no progress has been made on it. Until then I don’t see a way to do it.

How to get method list of one instance?
