### ISSUE TITLE
Package.swift doesn't run tests

### ISSUE THREAD

**Issue by helje5** [wickwirew/Runtime#7]
The new `Package.swift` w/ the old dir layout doesn't run the tests anymore:
```
helge@ZeaPro Runtime (feature/macos2)*$ swift test
Compile Swift Module 'Runtime' (41 sources)
error: no tests found; create a target in the 'Tests' directory
```

Neither on macOS nor on Linux.

**Comment by wickwirew** [comment]
In progress.

**Comment by wickwirew** [comment]
Sorry its taking a second. I have a new solution to make the test mapping for linux a little more automatic to make it easier to maintain.

**Comment by wickwirew** [comment]
Hey if you wouldn't mind checking out the `linux-tests` branch. There is a python script, in the `Scripts/` folder, to generate all of the test cases so nothing has to be managed. So if a test case is added in Xcode no one has to remember to update the `allTests` arrays. I don't have a Linux env right now thanks to hurricane Irma, so if you could try it out that'd be great
