### ISSUE TITLE
crash when Inherited from uikit

### ISSUE THREAD

**Issue by MinosJ** [wickwirew/Runtime#74]
when object inherited from uikit like:

> class TestView: UIView {}
   let _ = try? typeInfo(of: TestView.self)

it crash 
![image](https://user-images.githubusercontent.com/13655097/91376227-335cc680-e84f-11ea-8215-da7fd1eaef7c.png)

Is there any problem with me using this？ thanks

**Comment by wickwirew** [comment]
The provided example seems to work locally for me. What version of Runtime and Swift are you using?

**Comment by MinosJ** [comment]
Runtime: 2.1.1
Swift: 5.0

**Comment by wickwirew** [comment]
Looks like its been fixed in master for a while. Pushed a new 2.2.1 release and so it should be good now
