### ISSUE TITLE
Is this library safe to use on Linux?

### ISSUE THREAD

**Issue by ata-peppered** [wickwirew/Runtime#79]
I know this is a place for issues but couldn't find any better place to ask this question.

This library is great and I would like to use for one of my projects which runs on Linux - I believe at this time ABI stability is limited to systems running Darwin. I could be wrong about this. My question is - has this library been tested and is it safe to use on Linux?

Thanks

**Comment by wickwirew** [comment]
Yes it is safe/tested to use on linux. The PR checks actually check both linux and macos

**Comment by ata-peppered** [comment]
Wonderful! Thanks!
